name: 'crypto_snowflake_pipeline'
version: '1.0.0'
config-version: 2

profile: 'crypto_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models by folder and explicit model names
models:
  crypto_snowflake_pipeline:
    staging:
      +materialized: view
      stg_crypto_trades:
        +materialized: view
    marts:
      +materialized: incremental
      +incremental_strategy: merge
      +unique_key: trade_id
      fct_crypto_trades:
        +materialized: incremental
    streaming:
      +materialized: incremental
      +incremental_strategy: append
      hourly_crypto_summary:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key:
          - hourly_window
          - product_id
