USE ROLE ACCOUNTADMIN;

-- 1. Create Warehouse
CREATE OR REPLACE WAREHOUSE CRYPTO_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2. Create Database & Schema
CREATE DATABASE IF NOT EXISTS CRYPTO_DB;
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.PUBLIC;

-- 3. Create Role for Kafka Connector
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;

-- 4. Grant Privileges to the Role
GRANT USAGE ON WAREHOUSE CRYPTO_WH TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON DATABASE CRYPTO_DB TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA CRYPTO_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;

-- Allow role to create tables, stages, and pipes
GRANT CREATE TABLE ON SCHEMA CRYPTO_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STAGE ON SCHEMA CRYPTO_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE PIPE ON SCHEMA CRYPTO_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;

-- 5. Create User
CREATE USER IF NOT EXISTS KAFKA_CONNECTOR_USER
  DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
  DEFAULT_WAREHOUSE = CRYPTO_WH
  -- Must set RSA_PUBLIC_KEY here using the generated key
  RSA_PUBLIC_KEY = '<YOUR_PUBLIC_KEY_HERE>';

-- 6. Grant Role to User
GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;
